/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_project_SpringBootProject_Service_NativeStats */

#ifndef _Included_it_project_SpringBootProject_Service_NativeStats
#define _Included_it_project_SpringBootProject_Service_NativeStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_project_SpringBootProject_Service_NativeStats
 * Method:    nativeInt
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_it_project_SpringBootProject_Service_NativeStats_nativeInt
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
